### ISSUE TITLE
docker error?how to fixed this docker error

### ISSUE THREAD

**Issue by baifengbai** [Maicius/NcovWeRobot#1]
Traceback (most recent call last):
  File "src/robot/NcovWeRobotServer.py", line 268, in <module>
    start_server()
  File "src/robot/NcovWeRobotServer.py", line 241, in start_server
    itchat.auto_login(True)
  File "/usr/local/lib/python3.6/site-packages/itchat/components/register.py", line 32, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/usr/local/lib/python3.6/site-packages/itchat/components/login.py", line 49, in login
    picDir=picDir, qrCallback=qrCallback)
  File "/usr/local/lib/python3.6/site-packages/itchat/components/login.py", line 123, in get_QR
    utils.print_qr(picDir)
  File "/usr/local/lib/python3.6/site-packages/itchat/utils.py", line 83, in print_qr
    subprocess.call(['xdg-open', fileDir])
  File "/usr/local/lib/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xdg-open': 'xdg-open

**Comment by Maicius** [comment]
xdg-open 是用于弹出展示图片的，在docker中只能将二维码在控制台上打印出来，
修改NcovWeRobotServer中start_serve()函数：
    itchat.auto_login(True, enableCmdQR=2)

**Comment by baifengbai** [comment]
好的，谢谢
